apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: remote-aws
  namespace: pminkows-cicd
spec:
  clusterSet: remote-aws
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: remote-aws
  namespace: pminkows-cicd
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: cloud
              operator: "In"
              values:
                - Amazon
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: pminkows-cicd
spec:
  argoServer:
    cluster: argocd
    argoNamespace: pminkows-cicd
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: remote-aws
    namespace: pminkows-cicd